### Task 1. 

#### MapReduce

Use MapReduce to calculate the average housing price in each zip code and filter out records in which gross sqft is less than 500 and sale price is less than 100000. Round the average housing price to 2 decimals, and sort the output by housing price ascending.

In [1]:
import pandas as pd
import numpy as np

import csv
from functools import reduce
from multiprocessing import Pool

In [2]:
# !wget -O housingSalseSample.csv https://github.com/CUSP2022ADS/Data/raw/main/housingSalseSample.csv

In [3]:
import wget

housingSalseSample = wget.download("https://github.com/CUSP2022ADS/Data/raw/main/housingSalseSample.csv")

100% [......................................................] 6167298 / 6167298

In [4]:
# code here

housesale = pd.read_csv('housingSalseSample.csv',nrows=5)
housesale.head()

,BOROUGH,BLOCK,LOT,BUILDING CLASS CATEGORY,ADDRESS,ZIP CODE,GROSS SQUARE FEET,YEAR BUILT,SALE PRICE,SALE DATE
0,1,1170,1010,17 CONDOPS,"200 WEST 79TH STREET, 7P",10024.0,0.0,1975.0,551000,2011-07-28
1,4,1275,45,10 COOPS - ELEVATOR APARTMENTS,"35-35 75TH STREET, 304",11372.0,0.0,1941.0,338000,2011-05-20
2,3,5746,58,03 THREE FAMILY DWELLINGS,1249 65TH STREET,11219.0,3861.0,1910.0,1250000,2014-12-04
3,4,2086,50,10 COOPS - ELEVATOR APARTMENTS,"97-07 63 ROAD, 8F",11374.0,0.0,1955.0,253000,2016-03-09
4,4,5028,7,10 COOPS - ELEVATOR APARTMENTS,"38-15 149TH STREET, 1F",11354.0,0.0,1955.0,0,2016-12-30

In [5]:
# return necessary columns only
def returnInfo(record): #extract necessary fields from a data record (raw)
    return(record['ZIP CODE'],record['GROSS SQUARE FEET'],record['SALE PRICE'])

# filter out records in which gross sqft is less than 500 and sale price is less than 100000 (assuming NaN values to be zero)
def filterOutlier(record): #filter the records to keep only the year 2019
    # filter function must return True or False
    if record[1] == '': # converting NaN columns to 0 for using here
        SF = 0;
    else: 
        SF = int(float(record[1]))
    price = int(float(record[2]))    
    if ((SF >= 500) or (price >= 100000)):
        return True
    else:
        return False

# aggregate by zip
def ziplist(result,record):
    zipcode = record[0]
    price = int(float(record[2]))    
    result[zipcode] = result.get(zipcode,[]) + [price]
    return result

# get average for each zip

def averagePrice(record):
    zipcode, price = record[0], record[1]
    return [zipcode, round(sum(price)/len(price),2)]

# Sort the list based on 2nd element

def SortPrice(df):
    return(sorted(df, key = lambda x: x[1]))

In [6]:
with open('housingSalseSample.csv', 'r') as fi: #with a given dataset
    reader = csv.DictReader(fi) #line-by-line data reader 
    output = SortPrice(list(map(averagePrice,list(reduce(ziplist,filter(filterOutlier, #Remove records which have less than 500 sq feet and less than 100k price
                        map(returnInfo,reader) #extract necessary fields from the records 
                            ),{}
                        ).items()))))#initial value for the dictionary - {}
output

[['11411.0', 262348.84],
 ['11429.0', 268699.38],
 ['11434.0', 277268.68],
 ['10303.0', 280315.78],
 ['11412.0', 283849.54],
 ['11428.0', 290783.7],
 ['11414.0', 295958.4],
 ['11436.0', 297138.8],
 ['10305.0', 299889.46],
 ['11419.0', 299948.63],
 ['11415.0', 302316.43],
 ['11422.0', 302747.65],
 ['10466.0', 303430.78],
 ['11040.0', 305068.18],
 ['10310.0', 307735.65],
 ['10306.0', 311819.46],
 ['11203.0', 313288.37],
 ['11420.0', 313293.9],
 ['11416.0', 317098.23],
 ['11004.0', 317443.7],
 ['10469.0', 317906.29],
 ['11239.0', 323605.24],
 ['11413.0', 323696.59],
 ['10301.0', 325490.74],
 ['10308.0', 325815.12],
 ['11418.0', 329299.32],
 ['11433.0', 330573.94],
 ['10465.0', 331824.51],
 ['11427.0', 338360.05],
 ['11001.0', 345559.62],
 ['11207.0', 355817.03],
 ['10314.0', 356950.98],
 ['10312.0', 357979.78],
 ['10037.0', 365995.35],
 ['11421.0', 366170.62],
 ['11379.0', 375200.03],
 ['10302.0', 376299.63],
 ['10304.0', 380754.22],
 ['11236.0', 381775.26],
 ['11417.0', 386019.88],
 ['11364.0', 387499.19],
 ['10461.0', 392007.95],
 ['11375.0', 397096.27],
 ['11432.0', 402650.98],
 ['11369.0', 405427.83],
 ['10309.0', 409821.92],
 ['10470.0', 422471.48],
 ['10464.0', 427220.04],
 ['11692.0', 428976.67],
 ['11366.0', 434421.48],
 ['11234.0', 439726.54],
 ['11377.0', 445527.1],
 ['11357.0', 448209.53],
 ['11233.0', 451383.94],
 ['11367.0', 452722.78],
 ['11423.0', 453123.21],
 ['11370.0', 456829.98],
 ['11694.0', 458431.48],
 ['11693.0', 458535.1],
 ['11697.0', 460000.0],
 ['11235.0', 468812.18],
 ['11368.0', 470223.18],
 ['10307.0', 475297.69],
 ['11208.0', 478906.47],
 ['11005.0', 484526.89],
 ['11360.0', 484545.87],
 ['11435.0', 485297.83],
 ['11204.0', 491778.92],
 ['11372.0', 492122.22],
 ['11365.0', 492732.74],
 ['11212.0', 494385.69],
 ['10803.0', 497500.0],
 ['11361.0', 498901.84],
 ['11362.0', 501488.61],
 ['10044.0', 505316.0],
 ['11356.0', 506142.84],
 ['11228.0', 509627.82],
 ['11385.0', 510068.95],
 ['10472.0', 517344.43],
 ['11373.0', 518834.54],
 ['10471.0', 519149.03],
 ['11229.0', 527974.95],
 ['11214.0', 534402.16],
 ['11210.0', 536418.14],
 ['11213.0', 540511.5],
 ['11363.0', 542484.61],
 ['11355.0', 544385.56],
 ['11221.0', 589771.52],
 ['11105.0', 592134.91],
 ['10460.0', 594821.1],
 ['11209.0', 597275.08],
 ['11219.0', 598154.1],
 ['10463.0', 613614.05],
 ['10455.0', 614275.88],
 ['11220.0', 620245.66],
 ['11358.0', 621030.18],
 ['11104.0', 626536.67],
 ['11378.0', 632185.37],
 ['11691.0', 662684.16],
 ['11224.0', 669346.25],
 ['11223.0', 672767.36],
 ['11426.0', 675386.13],
 ['11103.0', 681140.38],
 ['10473.0', 682952.29],
 ['11225.0', 688911.67],
 ['11230.0', 753957.25],
 ['10462.0', 771768.64],
 ['10459.0', 788238.42],
 ['10034.0', 800856.51],
 ['11232.0', 804003.34],
 ['10456.0', 819230.24],
 ['11216.0', 829368.21],
 ['11205.0', 830460.24],
 ['11218.0', 833164.15],
 ['11109.0', 880422.31],
 ['10468.0', 883271.89],
 ['10467.0', 899271.27],
 ['10458.0', 949079.91],
 ['11237.0', 959386.14],
 ['11374.0', 963169.98],
 ['10457.0', 970101.63],
 ['10475.0', 983784.25],
 ['11238.0', 1016585.09],
 ['10474.0', 1032859.6],
 ['11226.0', 1037349.66],
 ['11206.0', 1063486.67],
 ['11102.0', 1105059.22],
 ['10280.0', 1119913.79],
 ['10453.0', 1152146.9],
 ['10454.0', 1201341.48],
 ['11354.0', 1224921.97],
 ['10031.0', 1236005.85],
 ['10035.0', 1269556.5],
 ['11222.0', 1288679.3],
 ['10027.0', 1289721.0],
 ['11211.0', 1293649.56],
 ['10005.0', 1297669.05],
 ['11215.0', 1327823.51],
 ['0.0', 1334767.3],
 ['10452.0', 1368150.52],
 ['10033.0', 1394995.05],
 ['11351.0', 1396205.0],
 ['11217.0', 1437748.79],
 ['10039.0', 1448825.65],
 ['10026.0', 1493119.89],
 ['10040.0', 1625031.39],
 ['11106.0', 1645431.64],
 ['11101.0', 1648226.92],
 ['11231.0', 1751963.16],
 ['11249.0', 1757938.68],
 ['10002.0', 1774646.44],
 ['10030.0', 1811079.28],
 ['11201.0', 1844069.83],
 ['10451.0', 1925370.21],
 ['10016.0', 1947113.69],
 ['10032.0', 2037073.99],
 ['10128.0', 2077537.69],
 ['10003.0', 2128179.77],
 ['10024.0', 2165901.31],
 ['10023.0', 2196968.82],
 ['10009.0', 2198902.13],
 ['10025.0', 2213285.9],
 ['10029.0', 2242422.14],
 ['10021.0', 2263578.76],
 ['10019.0', 2345856.71],
 ['10129.0', 2605000.0],
 ['10028.0', 2742856.7],
 ['10022.0', 2787247.27],
 ['11243.0', 2805000.0],
 ['10075.0', 2882953.28],
 ['10006.0', 3100626.18],
 ['10282.0', 3101208.23],
 ['10012.0', 3107812.62],
 ['10014.0', 3133032.17],
 ['10065.0', 3752055.74],
 ['10017.0', 3823689.9],
 ['10011.0', 3953399.79],
 ['10010.0', 4332563.76],
 ['10038.0', 4428218.48],
 ['10007.0', 4442959.68],
 ['10036.0', 4530796.97],
 ['10013.0', 4614642.33],
 ['10069.0', 6177687.31],
 ['10004.0', 8496856.55],
 ['10001.0', 9071827.02],
 ['10018.0', 9600316.3]]

In [7]:
'''grading function
please pass your output into this function and upload the generated csv file 
together with your notebook to your GitHub repo'''

def grading(output):
    import pandas as pd
    pd.DataFrame(output,columns=['zipcode','price']).to_csv('output1.csv',index=False)

grading(output)

### Task 2. 
#### multiprocessing and Chunk

In [8]:
# !wget -O ADSSession2Task2Data.csv https://raw.githubusercontent.com/CUSP2022ADS/Data/main/ADSSession2Task2Data.csv

In [9]:
import wget
wget.download("https://raw.githubusercontent.com/CUSP2022ADS/Data/main/ADSSession2Task2Data.csv")

100% [........................................................] 279369 / 279369

'ADSSession2Task2Data.csv'

Apply the chunk and MapReduce method to sum up each type's value in the synthetic dataset—only keep records which $Select$ value is 1, and read 1000 lines in each chunk. Use multiprocessing package to deploy the task to multi-cores. The output should only have two columns: type and total value.

Hint: filter function is not available in multiprocessing, implement an if-else function in the map or reduce step.

In [15]:
import tmp

In [16]:
from multiprocessing import Pool


with open('ADSSession2Task2Data.csv', 'r') as fi:
    reader = csv.DictReader(fi)
    chunk = []
    result = []
    # read 1000 rows in each chunk
    chunksize = 1000
    pool = Pool(8)
    for i, line in enumerate(reader):
        
        if (i % chunksize == 0 and i > 0):
            # MapReduce function for rows in one chunk
            output =  list(reduce(tmp.ValueList,
                      [ele for ele in list(pool.map(tmp.filterSelect,
                                                           pool.map(tmp.returnInfo,chunk)))
                                   if ele != []],{}).items())
            result += output
            chunk = []
            
        
        # add lines to chunk, and when the index
        # is 1000, 2000, etc, stop adding new lines
        # and start MapReduce functions
        chunk.append(line)
        
    # MapReduce function for the last chunk
    output =  list(reduce(tmp.ValueList,
              [ele for ele in list(pool.map(tmp.filterSelect,
                                                   pool.map(tmp.returnInfo,chunk)))
                           if ele != []],{}).items())
    result += output
    pool.close()

In [19]:
def reduceResults(result,record): #add rides from a new record to the dictionary accumilating type-origin-destination-time ridership
    Type,Value = record[0][0], record[1]
    result[(Type)] = result.get((Type),0) + float(Value)
    return result

In [23]:
result = list(reduce(reduceResults,result,{}).items())

In [24]:
'''grading function
please pass your output into this function and upload the generated csv file 
together with your notebook to your GitHub repo'''

def grading(output):
    import pandas as pd
    pd.DataFrame(output,columns=['Type','Value']).to_csv('output2.csv',index=False)

grading(result)